##########1D mesh generated by line segments#########
# Inputs:
#       a : left end, float64
#       b : right end, float64
#       n : number of elements, int
# Outputs:
#       MESH: partitioned line segment,
#             2-d array, left node | right node
function Mesh1D(a,b,n)
    h    = (b-a)/n
    MESH = zeros((n, 2)) # default is float64

    for i in 1:n
        MESH[i,1] = a + (i-1)*h
        MESH[i,2] = a + i*h
    end

    return MESH
end
####################################################

##########1D lagrange element############
# Inputs:
#       p: polynomial order
#       MESH: 1D mesh
# Outputs:
#
#
function Lagrange1D(p,MESH)
    


    return MESH
end
####################################################
